ITEM = input("ENTER ITEM:")
QUANTITY = int(input("ENTER THE QUANTITY:"))
UNITPRICE = float(input("ENTER UNIT PRICE:"))
DISCOUNT = 0.1 *(QUANTITY*UNITPRICE)
AMOUNTPAID = (QUANTITY*UNITPRICE) - DISCOUNT
print(DISCOUNT)
print(AMOUNTPAID)